# preload = /home/ky/Escritorio/fondos/god.png
# preload = /home/ky/Escritorio/fondos/girl-flowers.png
# preload = /home/ky/Escritorio/fondos/4.jpg
# preload = /home/ky/Escritorio/fondos/Cel/4.jpg
# preload = /home/ky/Escritorio/fondos/Cel/14.jpg
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# wallpaper = eDP-1,$HOME/Escritorio/fondos/cat_anime-girl-hand-in-hair.pngto/image.png
# wallpaper = HDMI-A-1,$HOME/Escritorio/fondos/cat_anime-girl-hand-in-hair.pngto/image.png

# wallpaper = DP-1, $HOME/Escritorio/fondos/girl-flowers.png
# wallpaper = DP-3,$HOME/Escritorio/fondos/god.png
# wallpaper = HDMI-A-1,$HOME/Escritorio/fondos/Cel/14.jpg

#enable splash text rendering over the wallpaper
# splash = true
 
#fully disable ipc
# ipc = off

wallpaper {
  monitor = DP-1
  # path = /home/ky/Escritorio/fondos/girl-flowers.png
  path = /home/ky/Escritorio/fondos/1387268.jpg
  fit_mode = fill
}

wallpaper {
  monitor = DP-3
  # path = /home/ky/Escritorio/fondos/Screenshot_1.png
  path = /home/ky/Escritorio/fondos/1363280.png
  fit_mode = fill
}
